adonisjs-community/adonis-packages

modules/adonis-responsive-attachment.yml

This PR adds the `adonis-responsive-attachment` addon. See more here: https://github.com/ndianabasi/adonis-responsive-attachment

Enlist `adonis-responsive-attachment` addon

---

modules/adonisjs-select-related.yml

- add select-related package to the list

docs: add select-related package

---

.gitignore
modules/table-driven-html-reporter.yml
modules/table-driven-tests.yml
website/composables/constants.ts

Add "Testing" category with 1 plugin and 1 reporter for japa

add two modules: table-driven-tests and table-driven-html-reporter

---

modules/ally-azure-ad.yml

add adonis-ally-azure-ad package to the authentication list

docs: add ally-azure-ad package

---

modules/adonis-queue.yml

This PR adds `@cavai/adonis-queue` package

Add adonis queue package

---

modules/flair.yml

This PR adds `flair` package https://github.com/mezielabs/flair.

Add flair package

---

modules/autoswagger.yml

Add adonis-autoswagger

---

.github/workflows/checks.yml
.github/workflows/on-push-to-main.yml
README.md
app/services/package_fetcher.ts
app/services/packages_fetcher.ts
commands/add_package.ts
config/cache.ts
content/categories.ts
content/packages/adonisjs-crud-generator.yml
content/packages/ally-gitlab.yml
content/packages/autoswagger.yml
content/packages/edge-vscode.yml
content/packages/eslint.yml
content/packages/mix-asset.yml
content/packages/sail.yml
content/packages/socket.io.yml
content/packages/swagger.yml
content/packages/vscode-extension.yml
resources/components/socials.vue
resources/pages/package/components/links.vue
tests/functional/commands/add_package.spec.ts
types/packages.ts

This PR remove space before and after ponction mark and update case of some words.

chore: fix case and space before and after ponctuation

---

resources/pages/home/main.vue

feat: scroll to top of list when clicking on next/prev page

---

content/packages/maintenance.yml

Only an extra yaml file is needed right?
I've also put it in the "Testing" category, was thinking about "development" or "testing"
Closes #42

Add maintenance package

---

content/packages/adonis-whatsapp.yml

It is the plugin for whatsapp business api integration best suitable for whatsapp based saas like wati

feat: added whatsapp plugin for v6 with multiple business api support

---

content/packages/advance-redis-rpc.yml

The package is based on reg2005/adonis5-redis-rpc. 
This package allows users to create multiple servers capable of communicating with each other. 
This package is compatible with V6 too. 
Thanks

feat: 🎸 add advance redis-rpc package for adonisjs v5 and v6

---

content/packages/advance-redis-rpc.yml

Fixed a typo. 
I apologize for the trouble.

fix: 🐛 updated package path

---

content/packages/attachment-advanced.yml
content/packages/edge-components.yml

Update compatibility edge-components and update attachment-advanced repo

update packages @jrmc

---

content/packages/adonisjs-permissions.yml

Roles and permissions for AdonisJs V6+

feat: add adonisjs-permissions

---

content/packages/acidiney-bull-queue.yml

docs: add @acidiney/bull-queue

---

content/packages/adonis-auditing.yml
content/packages/adonis-translatable.yml
content/packages/geolite2.yml

Just reorder some key and add v6 compatibility for geolite2.

fix: clean content file of my packages

---

app/services/packages_fetcher.ts
content/packages/adonisjs-jobs.yml

https://github.com/adonisjs-community/adonis-packages/blob/main/types/packages.ts#L79-L82

feat: include keywords in package filtering

---

content/packages/adonis-unpoly.yml

Package adonis 6, provider and middleware unpoly

chore: add @jrmc/adonis-unpoly

---

content/packages/girouette.yml

PS: The old version has been deleted from NPM.

Removing outdated Girouette package, and add the new one

---

content/packages/adonis-bullet.yml

AdonisJS helper to kill N+1 queries

Add package @7nohe/adonis-bullet

---

content/packages/outloud-adonis-scheduler

Adds [@outloud/adonis-scheduler](https://www.npmjs.com/package/@outloud/adonis-scheduler) package.

feat(packages): add @outloud/adonis-scheduler
